using System;
using System.Linq;
using PowerLanguage.Function;

namespace PowerLanguage.Strategy
{
	///<summary>
	///Episodic Pivot trade management for instruments that have gapped up on earnings or some other catalyst.
	///See notes on base class as it implements all the functionality for this signal.
	///</summary>
	public class _EpisodicPivotLX : _EpisodicPivotBase
	{
		//constants

		//types

		//properties

		//attribute

		//interface methods
		public _EpisodicPivotLX(object _ctx) : base(_ctx) { }

		//methods

	}
}