using System;
using System.Drawing;
using System.Linq;
using PowerLanguage.Function;
using ATCenterProxy.interop;

namespace PowerLanguage.Strategy {
	public class _PMMS_Dynamic_MM : PortfolioSignalObject {
    	
		[Input] public bool Debug { get; set; }		
		
		public _PMMS_Dynamic_MM(object _ctx):base(_ctx){}
				
		protected override void Create() {

		}
		protected override void StartCalc() {

		}
		protected override void CalcBar(){

		}
	}
}