using System;
using System.Drawing;
using System.Linq;
using PowerLanguage.Function;
using ATCenterProxy.interop;

namespace PowerLanguage.Strategy {
	
	/// <summary>
	/// Test trading breakouts of stocks that are up
	/// </summary>
	
	public class _PMMS_Test2 : PortfolioSignalObject {
		//constants
		
		
		//inputs
		
		
		//attributes		
		public _PMMS_Test2(object _ctx):base(_ctx){}

		protected override void Create()
		{

		}
		
		protected override void StartCalc()
		{

		}

		protected override void CalcBar()
		{

		}
	}
}