using System;
using System.Drawing;
using System.Linq;
using PowerLanguage.Function;

namespace PowerLanguage.Indicator
{
	[SameAsSymbol]
	public class _VCP : IndicatorObject
	{
		//constants


		//inputs


		//properties


		//attributes


		//interface methods
		public _VCP(object _ctx) : base(_ctx) { }

		protected override void Create()
		{

		}

		protected override void StartCalc()
		{

		}

		protected override void CalcBar()
		{

		}

		//methods


	}
}